nongshim_group_list = '/html/body/form[1]/div[3]/div/div[2]/div[2]/fieldset/div[1]/select'
id_edit = '/html/body/form[1]/div[3]/div/div[2]/div[2]/fieldset/div[1]/div[2]/div/div[1]/input'
ps_edit = '/html/body/form[1]/div[3]/div/div[2]/div[2]/fieldset/div[1]/div[2]/div/div[2]/input'
login_button = '/html/body/form[1]/div[3]/div/div[2]/div[2]/fieldset/div[1]/div[2]/button'
work_activity= '/html/body/div[2]/div[2]/div/div/div/ul/li[3]/'
test = '/html/body/div[2]/div[1]/div/div[3]/div/ul[1]/li[1]'
