name : start GithubAction

on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses : actions/checkout@v2
    #run뒤에 실제 작동하는 코드 넣어야됨
    - name : hello world 출력
      run : echo Hello world!!
    - name : 디렉토리 출력
      run : dir
    - name : 파이썬 버전 출력
      run : python -V
    - name : 파이썬 파일 실행
      run : python crawling.py
    
