name : start GithubAction

on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses : actions/checkout@v2
    #run뒤에 실제 작동하는 코드 넣어야됨
    - name : hello world 출력
      run : echo Hello world!!
    - name : 디렉토리 출력
      run : dir
    - name : 파이썬 버전 출력
      run : python -V
    - name : 파이썬 패키지 확인
      run : pip list
    - name : pip 업그레이드
      run : python -m pip install --upgrade pip
    - name : 필요한 패키지 설치
      run : pip install -r requirements.txt
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE/" >> $GITHUB_ENV

    - name : 파이썬 파일 실행
      run : python crawling.py
    
